### ISSUE TITLE
`pip install` not working

### ISSUE THREAD

**Issue by harshcurious** [IBArbitrary/jupyterlab_gruvbox_dark#1]
Running the pip install returns the following:
```sh
python -m pip install jupyterlab-gruvbox-dark                                                                                                   ─╯
ERROR: Could not find a version that satisfies the requirement jupyterlab-gruvbox-dark (from versions: none)
ERROR: No matching distribution found for jupyterlab-gruvbox-dark
```
Looking for `jupyterlab-gruvbox-dark` on [PyPi](https://pypi.org/search/?q=+jupyterlab_gruvbox_dark) also returns nothing. Could you update the package?

**Comment by IBArbitrary** [comment]
I don't think I ever added the repository to PyPi. But you can install this via `jupyter labextension install IBArbitrary/jupyterlab_gruvbox_dark` and that seems to work, with negligible hiccups. I made the package in piecemeal manner from various sources, primarily for personal needs, and I myself am not sure how the packaging workflows are handled. So feel free to fork and implement any changes that you wish to see.

**Comment by IBArbitrary** [comment]
@harshcurious I have updated the theme and uploaded to PyPi. Please check if `pip install` works now. Cheers.
